name: TechOn
favicon: null
layout_spectrum: 0.30530708166770637
typography_spectrum: 0.7653783911373466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6257674267981201
  lightness: 0.7163606877438724
  saturation: 0.04145071795210242
  rhythmicContrast: 0.4120575711131096
purpose: []
